#!/bin/bash
#
# KDElibs/win32 Build Environment
#

# Copy kde_env_custom.template to kde_env_custom and this it's paths if needed:

source "kde_env_custom" || exit 1

if [ -n "$MSVC" ] ; then
	export PATH="$MSVC\\bin;$PATH" #to avoid conflict with, say, GNU link
	export INCLUDE="$MSVC\\include;$INCLUDE"
fi

# Generic settings
export KDELIBS=$KDEWIN\\tdelibs  # KDElibs/win32 source directory
export INCLUDE="$KDELIBS\\win;$KDELIBS;$KDELIBS\\tdecore;$KDELIBS\\tdefx;$KDELIBS\\tdeprint;$KDELIBS\\tdeui;$KDELIBS\\tdemdi;$KDELIBS\\dcop;$KDELIBS\\tdeio;$KDELIBS\\tdeio\\tdeio;$KDELIBS\\tdeio\\tdefile;$INCLUDE"

# Version information for binaries
# We're changing this from time to time

export KDE_VER_MAJ=3
export KDE_VER_MIN=5
export KDE_VER_PAT=0
export KDE_VER=$KDE_VER_MAJ$KDE_VER_MIN$KDE_VER_PAT

# Utils

export MAKE="nmake /NOLOGO"
